name: $(Build.DefinitionName) $(Rev:rrrr)

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - Samples/AzureDevOps/Scripts/* # Modify path as required
      - Samples/AzureDevOps/Settings/* # Modify path as required
      - Samples/AzureDevOps/Solutions/* # Modify path as required

stages:
  - stage: buildArtifacts
    displayName: 'Build Artifacts'
    jobs:
    # Build script artifacts
    - job: buildScripts
      pool:
        vmImage: 'windows-latest'
      displayName: 'Build Scripts'
      steps:
        - checkout: self
          persistCredentials: true
        - task: CopyFiles@2
          name: copyScriptFilesFromSourceToArtifact
          displayName: Copy Script Files from Source to Artifact
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)/Samples/AzureDevOps/Scripts' # Modify path as required
            Contents: '**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)/Build/Scripts'  
        - task: PublishBuildArtifacts@1
          name: publishScriptBuildArtifacts
          displayName: Publish Scripts Build Artifact
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/Build/Scripts'
            ArtifactName: 'Scripts'
            publishLocation: 'Container'  

    # Build settings artifacts        
    - job: buildSettings
      pool:
        vmImage: 'windows-latest'
      displayName: 'Build Settings'
      steps:
        - checkout: self
          persistCredentials: true
        - task: CopyFiles@2
          name: copySettingsFilesFromSourceToArtifact
          displayName: Copy Settings Files from Source to Artifact
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)/Samples/AzureDevOps/Settings' # Modify path as required
            Contents: '**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)/Build/Settings'  
        - task: PublishBuildArtifacts@1
          name: publishSettingsBuildArtifacts
          displayName: Publish Settings Build Artifact
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/Build/Settings'
            ArtifactName: 'Settings'
            publishLocation: 'Container'

    # Build solutions artifacts        
    - job: buildSolutions
      pool:
        vmImage: 'windows-latest'
      displayName: 'Build Solutions'
      steps:
        - checkout: self
          persistCredentials: true
        - task: PowerPlatformToolInstaller@2
          name: installPowerPlatformTools
          displayName: Install Power Platform Tools
          inputs:
            DefaultVersion: true
        - task: PowerPlatformPackSolution@2
          name: packDataverseSolution
          displayName: Pack Dataverse Solution
          inputs:
            SolutionType: Both
            SolutionSourceFolder: $(Build.SourcesDirectory)/Samples/AzureDevOps/Solutions/EnvironmentRetention # Modify path as required
            SolutionOutputFile: $(Build.ArtifactStagingDirectory)/Build/Solutions/EnvironmentRetention.zip 
        - task: PublishBuildArtifacts@1
          name: publishBuildArtifacts
          displayName: Publish Solutions Build Artifact
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/Build/Solutions'
            ArtifactName: 'Solutions'
            publishLocation: 'Container'              