name: $(Build.DefinitionName) $(Rev:rrrr)

trigger: none

parameters:
  - name: SolutionName
    displayName: "Solution Unique Name"
    type: string
    
  - name: CommitMessage
    displayName: "Commit Message"
    type: string

variables:
  - group: Generic Variables # This Variable Group will need creating in your Azure DevOps Project under Pipelines > Library. Remember also to grant the pipelines access to the Variable Groups and link them together
    

stages:
  - stage: exportUnpackAndCommitSolution
    displayName: 'Export, Unpack and Commit Solution'
    variables:
    - group: 'DEV Environment Variables' # This Variable Group will need creating in your Azure DevOps Project under Pipelines > Library. Remember also to grant the pipelines access to the Variable Groups and link them together
    jobs:
    - job: exportUnpackAndCommitSolution
      pool:
        vmImage: 'windows-latest'
      displayName: 'Export, Unpack and Commit Solution'
      steps:
      - template: ../Templates/commit-solution-template.yml
        parameters:
              SolutionName: ${{ parameters.SolutionName }}
              CommitMessage: ${{ parameters.CommitMessage }}
          